language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get update
  - sudo apt-get install libfftw3-dev
script:
  - cargo test --workspace --exclude light-curve-python
  - cargo bench --workspace --exclude light-curve-python
