language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --manifest-path light-curve/Cargo.toml
  - cargo test --manifest-path light-curve-common/Cargo.toml
  - cargo test --manifest-path light-curve-feature/Cargo.toml
  - cargo test --manifest-path light-curve-interpol/Cargo.toml
