[package]
name = "light-curve-python"
version = "0.1.0"
edition = "2018"
authors = ["Konstantin Malanchev <hombit@gmail.com>"]
license = "GPL-3.0-or-later"

[lib]
name = "light_curve"
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
light-curve-feature = { version = "0.1.12", default-features = false, features = ["fftw-system"] }
numpy = "~0.8"

[dependencies.pyo3]
version = "~0.9"
features = ["extension-module"]

[package.metadata.maturin]
requires-dist = ["numpy"]
classifier = ["Intended Audience :: Science/Research", "License :: OSI Approved :: MIT License", "Programming Language :: Python", "Programming Language :: Python :: 3 :: Only", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Rust", "Topic :: Scientific/Engineering :: Astronomy"]
