name: Publish Python packages

on:
  push:
    tags:
      - light-curve-python-v*

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    defaults:
      run:
        working-directory: python

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install maturin
      run: pip install maturin
    - name: Publish
      run: maturin publish --no-strip -u __token__ -p ${{ secrets.PYPI_TOKEN }}
