name: Publish Python packages

on:
  push:
    tags:
      - light-curve-python-v*

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    defaults:
      run:
        working-directory: light-curve-python

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install tox and maturin
      run: pip install tox maturin
    - name: Run Python tests
      run: tox -p -q
    - name: Publish Linux packages
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: docker run --rm -v $(pwd):/io konstin2/maturin publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
    - name: Publish macOS packages
      if: ${{ matrix.os != 'ubuntu-20.04' }}
      run: maturin publish --no-sdist -u __token__ -p ${{ secrets.PYPI_TOKEN }}
