name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test
    - name: Run benchmarks
      run: cargo bench
