name: Test

on: [push, pull_request]

jobs:
  rust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install FFTW
      run: |
        sudo apt-get update
        sudo apt-get install libfftw3-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets --all-features --workspace --exclude light-curve-python
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --exclude light-curve-python
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Run code analysis
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --exclude light-curve-python --all-targets --all-features -- -D warnings

  python:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: python

    steps:
    - uses: actions/checkout@v2
    - name: Install FFTW
      run: |
        sudo apt-get update
        sudo apt-get install libfftw3-dev
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install maturin
      run: pip install maturin
    - name: Build package with static FFTW
      run: maturin build
    - name: Build package with dynamic FFTW
      run: maturin build --manylinux=off --cargo-extra-args="--no-default-features --features fftw-dynamic"
    - name: Build package with dynamic MKL
      run: maturin build --manylinux=off --cargo-extra-args="--no-default-features --features mkl-dynamic"
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Run code analysis
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --all-features -- -D warnings
